// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: balance_records_crud.sql

package db_api

import (
	"context"
	"database/sql"
	"time"
)

const createBalanceRecord = `-- name: CreateBalanceRecord :exec
insert into balance_records (
    amount, date, origin_tract
) values (
    ?, ?, ?
)
`

type CreateBalanceRecordParams struct {
	Amount      float64
	Date        time.Time
	OriginTract sql.NullInt64
}

func (q *Queries) CreateBalanceRecord(ctx context.Context, arg CreateBalanceRecordParams) error {
	_, err := q.db.ExecContext(ctx, createBalanceRecord, arg.Amount, arg.Date, arg.OriginTract)
	return err
}

const deleteBalanceRecord = `-- name: DeleteBalanceRecord :exec
delete from balance_records
where id = ?
`

func (q *Queries) DeleteBalanceRecord(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteBalanceRecord, id)
	return err
}

const listBalanceRecords = `-- name: ListBalanceRecords :many
select id, amount, date, origin_tract
from balance_records
`

func (q *Queries) ListBalanceRecords(ctx context.Context) ([]BalanceRecord, error) {
	rows, err := q.db.QueryContext(ctx, listBalanceRecords)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BalanceRecord
	for rows.Next() {
		var i BalanceRecord
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.Date,
			&i.OriginTract,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
