// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: delete_generated.sql

package db_api

import (
	"context"
)

const deleteGeneratedBalanceRecords = `-- name: DeleteGeneratedBalanceRecords :exec
delete from balance_records
where origin_tract is not null
`

func (q *Queries) DeleteGeneratedBalanceRecords(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteGeneratedBalanceRecords)
	return err
}

const deleteGeneratedTracts = `-- name: DeleteGeneratedTracts :exec
delete from tracts
`

func (q *Queries) DeleteGeneratedTracts(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteGeneratedTracts)
	return err
}
