// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: goals.sql

package db_api

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGoal = `-- name: CreateGoal :exec
insert into goals (
    amount, comment, hidden, index
) values (
    $1, $2, $3, $4
)
`

type CreateGoalParams struct {
	Amount  float64
	Comment pgtype.Text
	Hidden  bool
	Index   int32
}

func (q *Queries) CreateGoal(ctx context.Context, arg CreateGoalParams) error {
	_, err := q.db.Exec(ctx, createGoal,
		arg.Amount,
		arg.Comment,
		arg.Hidden,
		arg.Index,
	)
	return err
}

const deleteGoal = `-- name: DeleteGoal :exec
delete from goals
where id = $1
`

func (q *Queries) DeleteGoal(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteGoal, id)
	return err
}

const deleteGoalTxnsSince = `-- name: DeleteGoalTxnsSince :exec
delete from txns
where
    goal_id is not null
    and ts >= $1
`

func (q *Queries) DeleteGoalTxnsSince(ctx context.Context, ts pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteGoalTxnsSince, ts)
	return err
}

const listGoals = `-- name: ListGoals :many
select id, amount, comment, hidden, index
from goals
`

func (q *Queries) ListGoals(ctx context.Context) ([]Goal, error) {
	rows, err := q.db.Query(ctx, listGoals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Goal
	for rows.Next() {
		var i Goal
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.Comment,
			&i.Hidden,
			&i.Index,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoalsForCalc = `-- name: ListGoalsForCalc :many
select goals.id, goals.amount, goals.comment, goals.hidden, goals.index
from goals
RIGHT JOIN txns on txns.goal_id = goals.id
order by goals.index
`

type ListGoalsForCalcRow struct {
	ID      pgtype.Int4
	Amount  pgtype.Float8
	Comment pgtype.Text
	Hidden  pgtype.Bool
	Index   pgtype.Int4
}

func (q *Queries) ListGoalsForCalc(ctx context.Context) ([]ListGoalsForCalcRow, error) {
	rows, err := q.db.Query(ctx, listGoalsForCalc)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGoalsForCalcRow
	for rows.Next() {
		var i ListGoalsForCalcRow
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.Comment,
			&i.Hidden,
			&i.Index,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
