// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db_api

import (
	"database/sql"
	"time"
)

type BalanceRecord struct {
	ID          int64
	Amount      float64
	Date        time.Time
	OriginTract sql.NullInt64
}

type Rtract struct {
	ID      int64
	Rrule   string
	Desc    string
	Amount  float64
	ReqsAck bool
}

type RtractsToTract struct {
	RtractID int64
	TractID  int64
}

type Target struct {
	ID      int64
	Amount  float64
	Desc    string
	Order   int64
	TractID sql.NullInt64
}

type Tract struct {
	ID     int64
	Type   string
	Date   time.Time
	Amount float64
	Acked  bool
}
