// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db_api

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Goal struct {
	ID      int32
	Amount  float64
	Comment pgtype.Text
	Index   int32
}

type Rtxn struct {
	ID      int32
	Amount  float64
	Comment pgtype.Text
	Rrule   string
}

type Txn struct {
	ID      int32
	Amount  float64
	Comment pgtype.Text
	Ts      pgtype.Timestamptz
	RtxnID  pgtype.Int4
	GoalID  pgtype.Int4
}
