// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db_api

import (
	"database/sql"
	"time"
)

type BalanceRecord struct {
	ID     int64
	Amount float64
	Date   time.Time
}

type Rtract struct {
	ID      int64
	Rrule   string
	Desc    string
	Amount  float64
	ReqsAck bool
}

type Target struct {
	ID     int64
	Amount float64
	Desc   string
	Order  int64
}

type Tract struct {
	ID       int64
	Date     time.Time
	Amount   float64
	Acked    bool
	TargetID sql.NullInt64
	RtractID sql.NullInt64
}
