// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rtracts_crud.sql

package db_api

import (
	"context"
)

const createRTract = `-- name: CreateRTract :exec
insert into rtracts (
    rrule, desc, amount, reqs_ack
) values (
    ?, ?, ?, ?
)
`

type CreateRTractParams struct {
	Rrule   string
	Desc    string
	Amount  float64
	ReqsAck bool
}

func (q *Queries) CreateRTract(ctx context.Context, arg CreateRTractParams) error {
	_, err := q.db.ExecContext(ctx, createRTract,
		arg.Rrule,
		arg.Desc,
		arg.Amount,
		arg.ReqsAck,
	)
	return err
}

const listRTracts = `-- name: ListRTracts :many
select id, rrule, "desc", amount, reqs_ack
from rtracts
`

func (q *Queries) ListRTracts(ctx context.Context) ([]Rtract, error) {
	rows, err := q.db.QueryContext(ctx, listRTracts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rtract
	for rows.Next() {
		var i Rtract
		if err := rows.Scan(
			&i.ID,
			&i.Rrule,
			&i.Desc,
			&i.Amount,
			&i.ReqsAck,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
