// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rtxns.sql

package db_api

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRtxn = `-- name: CreateRtxn :exec
insert into rtxns (
    amount, comment, rrule
) values (
    $1, $2, $3
)
`

type CreateRtxnParams struct {
	Amount  float64
	Comment pgtype.Text
	Rrule   string
}

func (q *Queries) CreateRtxn(ctx context.Context, arg CreateRtxnParams) error {
	_, err := q.db.Exec(ctx, createRtxn, arg.Amount, arg.Comment, arg.Rrule)
	return err
}

const listRtxns = `-- name: ListRtxns :many
select id, amount, comment, rrule
from rtxns
`

func (q *Queries) ListRtxns(ctx context.Context) ([]Rtxn, error) {
	rows, err := q.db.Query(ctx, listRtxns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rtxn
	for rows.Next() {
		var i Rtxn
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.Comment,
			&i.Rrule,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRtxnsEnds = `-- name: ListRtxnsEnds :many
with latest_txns as (
    select rtxn_id, max(ts) as ts
    from txns
    where rtxn_id is not null
    group by rtxn_id
)
select rt.id, rt.amount, rt.comment, rt.rrule, t.ts
from rtxns rt
join latest_txns t on rt.id = t.rtxn_id
`

type ListRtxnsEndsRow struct {
	ID      int32
	Amount  float64
	Comment pgtype.Text
	Rrule   string
	Ts      interface{}
}

func (q *Queries) ListRtxnsEnds(ctx context.Context) ([]ListRtxnsEndsRow, error) {
	rows, err := q.db.Query(ctx, listRtxnsEnds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRtxnsEndsRow
	for rows.Next() {
		var i ListRtxnsEndsRow
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.Comment,
			&i.Rrule,
			&i.Ts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
