// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: targets_crud.sql

package db_api

import (
	"context"
)

const createTarget = `-- name: CreateTarget :exec
insert into targets (
    amount, desc, "order"
) values (
    ?, ?, ?
)
`

type CreateTargetParams struct {
	Amount float64
	Desc   string
	Order  int64
}

func (q *Queries) CreateTarget(ctx context.Context, arg CreateTargetParams) error {
	_, err := q.db.ExecContext(ctx, createTarget, arg.Amount, arg.Desc, arg.Order)
	return err
}

const deleteTarget = `-- name: DeleteTarget :exec
delete from targets
where id = ?
`

func (q *Queries) DeleteTarget(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTarget, id)
	return err
}

const listTargets = `-- name: ListTargets :many
select id, amount, "desc", "order", tract_id
from targets
`

func (q *Queries) ListTargets(ctx context.Context) ([]Target, error) {
	rows, err := q.db.QueryContext(ctx, listTargets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Target
	for rows.Next() {
		var i Target
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.Desc,
			&i.Order,
			&i.TractID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
