// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tracts_crud.sql

package db_api

import (
	"context"
	"database/sql"
	"time"
)

const createTract = `-- name: CreateTract :one
insert into tracts (
    date, amount, acked, target_id, rtract_id
) values (
    ?, ?, ?, ?, ?
)
returning id
`

type CreateTractParams struct {
	Date     time.Time
	Amount   float64
	Acked    bool
	TargetID sql.NullInt64
	RtractID sql.NullInt64
}

func (q *Queries) CreateTract(ctx context.Context, arg CreateTractParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createTract,
		arg.Date,
		arg.Amount,
		arg.Acked,
		arg.TargetID,
		arg.RtractID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
