// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tracts_crud.sql

package db_api

import (
	"context"
	"time"
)

const createTract = `-- name: CreateTract :one
insert into tracts (
    type, date, amount, acked
) values (
    ?, ?, ?, ?
)
returning id
`

type CreateTractParams struct {
	Type   string
	Date   time.Time
	Amount float64
	Acked  bool
}

func (q *Queries) CreateTract(ctx context.Context, arg CreateTractParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createTract,
		arg.Type,
		arg.Date,
		arg.Amount,
		arg.Acked,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
