// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: truncation.sql

package db_api

import (
	"context"
)

const deleteAllBalanceRecords = `-- name: DeleteAllBalanceRecords :exec
delete from balance_records
`

func (q *Queries) DeleteAllBalanceRecords(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllBalanceRecords)
	return err
}

const deleteAllRTracts = `-- name: DeleteAllRTracts :exec
delete from rtracts
`

func (q *Queries) DeleteAllRTracts(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllRTracts)
	return err
}

const deleteAllTargets = `-- name: DeleteAllTargets :exec
delete from targets
`

func (q *Queries) DeleteAllTargets(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllTargets)
	return err
}
