// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: txns.sql

package db_api

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTxn = `-- name: CreateTxn :one
insert into txns (
    amount, comment, ts, rtxn_id, goal_id
) values (
    $1, $2, $3, $4, $5
)
returning id
`

type CreateTxnParams struct {
	Amount  float64
	Comment pgtype.Text
	Ts      pgtype.Timestamptz
	RtxnID  pgtype.Int4
	GoalID  pgtype.Int4
}

func (q *Queries) CreateTxn(ctx context.Context, arg CreateTxnParams) (int32, error) {
	row := q.db.QueryRow(ctx, createTxn,
		arg.Amount,
		arg.Comment,
		arg.Ts,
		arg.RtxnID,
		arg.GoalID,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const listTxnsSince = `-- name: ListTxnsSince :many
select id, amount, comment, ts, rtxn_id, goal_id
from txns
where ts >= $1 and rtxn_id = $2
order by ts asc
`

type ListTxnsSinceParams struct {
	Since  pgtype.Timestamptz
	RtxnID pgtype.Int4
}

func (q *Queries) ListTxnsSince(ctx context.Context, arg ListTxnsSinceParams) ([]Txn, error) {
	rows, err := q.db.Query(ctx, listTxnsSince, arg.Since, arg.RtxnID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Txn
	for rows.Next() {
		var i Txn
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.Comment,
			&i.Ts,
			&i.RtxnID,
			&i.GoalID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
