// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Balance struct {
	ID          int64
	Amount      float64
	Date        int64
	OriginTract sql.NullInt64
}

type Rtract struct {
	ID     int64
	Rrule  string
	Desc   string
	Amount float64
}

type RtractToTract struct {
	RtractID int64
	TractID  int64
}

type Target struct {
	ID      int64
	Amount  float64
	Desc    string
	Order   int64
	TractID int64
}

type Tract struct {
	ID      int64
	Type    string
	Date    int64
	Amount  float64
	Ack     bool
	ReqsAck bool
}
