// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const listGTractsAfter = `-- name: ListGTractsAfter :many
select t.id, t.type, t.date, t.amount, t.ack, t.reqs_ack
from rtract_to_tract rtt
join tracts t on rtt.tract = t.id
where rtt.rtract_id = ?1
order by date asc
`

func (q *Queries) ListGTractsAfter(ctx context.Context, targetRtract int64) ([]Tract, error) {
	rows, err := q.db.QueryContext(ctx, listGTractsAfter, targetRtract)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tract
	for rows.Next() {
		var i Tract
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Date,
			&i.Amount,
			&i.Ack,
			&i.ReqsAck,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
